# Site settings
title: Lukas Kollmann 
email: hello@lukaskollmann.at
description: "My name is Lukas Kollmann and I'm a freelance designer based in Graz, Austria. The most entertaining thing for me is to create content that works properly and looks appealing. At the moment, I really enjoy motion design and cinematography, as well as web- and app design. If needed, I can also handle branding- and illustration tasks, plus, I have some basic knowledge in front end development."
baseurl: "" # the subpath of your site, e.g. /blog/
url: "lukaskollmann.github.io" # the base hostname & protocol for your site
twitter_username: lukaskollmann
github_username:  LukasKollmann
facebook_username:  lukas.kollmann.50

# Build settings
markdown: kramdown
